### PR TITLE
Fix doctest for Inspect.Algebra

### PR DESCRIPTION
**Pull request by matsubara0507**
Fixed failed test about doctest for Inspect.Algebra (1-4) of issue https://github.com/lpil/exfmt/issues/87

(I think,) The cause is this commits:  https://github.com/elixir-lang/elixir/commit/f0d8219

I fixed doctest, but I don't know that there is no problem for behavior.

## Description

This pull request fixes.

## Checklist

- [ ] The change has been discussed in a GitHub issue.
- [ ] There are tests for the new functionality.
- [x] I agree to adhere to the code of conduct.

### CODE REVIEW

**Comment by lpil** [comment]
Seems there are a lot of failing tests now, why is this?

**Comment by matsubara0507** [comment]
I think https://github.com/elixir-lang/elixir/commit/455c2c3 is a commit for many new failures. 
The above commit changed to a method to collect comments using side effects.
By the way, I fixed these failures with https://github.com/matsubara0507/exfmt/commit/e98b0ee .

**Comment by lpil** [comment]
Wonderful, would you mind making a pull request with that fix first?

**Comment by matsubara0507** [comment]
OK

**Comment by matsubara0507** [comment]
Done

**Comment by lpil** [comment]
Closing this as the project is deprecated. Thank you!

**Pull request closed without merging**
