### PR TITLE
mention quick installation method

### PR DESCRIPTION
**Pull request by Tuxified**
## Description

I think it would help to include a brief method for installation (besides adding it to your project), so folks can start using it asap ;)

## Checklist

- [ ] The change has been discussed in a GitHub issue.
My bad, I didn't look for contribution instructions
- [ ] There are tests for the new functionality.
I don't think this applies/is needed?
- [x] I agree to adhere to the code of conduct.

### CODE REVIEW

**Comment by lpil** [comment]
These installation instructions are incorrect I'm afraid, Elixir 1.4 isn't supported. To install you will need to be running off the master branch of Elixir.

**Comment by Tuxified** [comment]
I tried this step with the current version (1.5.1) and it works fine on my machine™ ;)

I'll try running the tests as well and report back?

**Comment by lpil** [comment]
It will install but several features will be broken due to the lack of certain features in the older Elixir parser. I may have to add an explicit check so that it fails to install on older versions as people are reporting features as broken when using older unsupported versions of Elixir.

**Comment by Tuxified** [comment]
I see, that's too bad. Perhaps it's a good idea to mention that requirement in the README?
I was wondering if it's perhaps possible to package a newer parser with this package, but then again, that's asking for trouble :)

Already looking forward to 1.6 then ;)

**Comment by lpil** [comment]
Was planning to package the 1.6-dev runtime into an escript and distribute that. :)

Yet to do it though I'm afraid

**Comment by lpil** [comment]
I've added some notes to the README, closing this. Thank you for your help :)

**Pull request closed without merging**
